
[build]
target = "riscv32i-unknown-none-elf"

[target.riscv32i-unknown-none-elf]
linker = "riscv32-none-elf-ld"
rustflags = [
    "-C", "target-cpu=generic-rv32",
    "-C", "target-feature=+zmmul,+zicond,+zifencei,-a,-c,-b,-zba,-zbb,-zbc,-zbkb,-zbkc,-zbkx,-zbs",
    "-C", "link-args=-nostdlib",
    "-C", "link-arg=-Tld/hardware.ld",
    "-C", "link-arg=-Tld/common.ld",
    "-C", "link-arg=--no-relax",
    "-C", "force-unwind-tables=no",
    "-C", "link-arg=--gc-sections",
    # "-C", "link-arg=-Wl,--no-warn-rwx-segments",
]
